### ISSUE TITLE
create a list of pictures

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#1]
## Value Proposition
**As a** user
**I want to** see a list of pictures
**so that** i can see photos of my favourite movies and series.
​

## Description
![Image](https://user-images.githubusercontent.com/113838567/201916361-0c9cc202-5aef-4ede-b373-e82033c674af.png)

​
## Acceptance Criteria
- [x] a headline of the list is visible
- [x] a list of squared pictures is visible
- [x] picture size is 100x100px

​
## Tasks
- [x] create a feature branch called display-feature
- [x] create a db.json with an array of dummy data of my favourite movies and series
  - [x] properties: id, title, year, genre, picture and plot
  - [x] use unlicensed pictures from themoviedb.org       
- [x] write a function that fetches the pictures of each object of said array
- [x] create an unordered list element with the title "series & movies" as h1
- [x] display the fetched data in the list

## Complexity Estimation
M
