### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#12]
## Value Proposition

**As a** user
**I want to** the app have a fitting design
**so that** i have easier access.
​

## Description
design the app.
​

## Acceptance Criteria

- [x] the app is logically structured
- [x] the pages have a "matching" design
- [x] the app is accessible
      ​

## Tasks

- [x] create a branch called feature/design
- [x] create a color scheme
- [x] use styled components
- [x] use lighthouse extension to test the app
      ​

## Complexity
M
