### ISSUE TITLE
add api

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#13]
**As a** developer
**I need to** fetch data from an api
**so that** i can search for any series/movie there is.
​
## Description
the search accesses moviedb.
​
## Acceptance Criteria
​
- [ ] the search bar allows to search for any series/movies
- [ ] the page gives an error when something is wrong with getting the data
- [ ] the results are displayed on the landing page
​
## Tasks
​
- [ ] create a branch called feature/api
- [ ] re-write the fetch function so it matches the moviedb requirements
   - [ ] implement api key
   - [ ] adjust properties
- [ ] fetch data from url instead of array
