### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#15]
## Value Proposition
​
**As a** user
**I want** to see a favicon
**so that** i can easily find the browser tab of my page.
​
## Description
​

## Acceptance Criteria
​
- [ ] the page has a favicon
​
## Tasks
​
- [ ] create a logo.svg
- [ ] convert to .ico
- [ ] implement in head of all pages
