### ISSUE TITLE
create a detail page

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#2]
## Value Proposition
**As a** user
**I want to** go to a detail page of a movie/series that interests me,
**so that** I can get further informations about it.
​

## Description

![Image](https://user-images.githubusercontent.com/113838567/201869708-a4fee971-bf38-446f-b12a-a66131e8490d.png)

​
## Acceptance Criteria
- [x] title, year, genre and plot should be displayed
- [x] title works as a headline of the page
- [x] the same picture as on the list page should be displayed for each movie/series
- [x] picture size is 384.0x259.2 px  
- [x] when clicking/tapping on the picture the route switches to the respective details page of the movie/series
 - [x] when clicking/tapping on the "go back to list" link, the user is redirected to the landing page
​

## Tasks
- [x] create a feature branch called detail-page
- [x] create a detail page with a picture place holder and an unordered list element 
  list properties:
  - title as a `<h1>` element
  - year
  - genre
  - plot
- [x] fetch the picture and above listed properties from existing db.json
- [x] create routing from the list page items to the respective detail pages
   - [x] import link from 'next/link'
   

## Estimated Complexity
17XL

**Comment by JessicaLoers** [comment]
Hi @WilhelmAlfke ✌️

I would like to suggest that you write the story from the user's perspective, because the feature (showing movie/series details) has a very clear benefit/value for the user.

Here is my suggestion:
**Value Proposition**
As a user
I want go to a details page of a movie/series that interests me,
so that I can get further informations about it

Value Propositions are structured as follows: 
As a User `<ROLE>` 
I want to `<ACTIVITY>`
so that I `<DESIRED USER VALUE>`

**Acceptance Criteria**
- [ ]  ~~each picture on the list page works as a hotlink to its detail page~~
**👇This one is more detailed and describes the user interaction:**
- [ ]  when clicking/tapping on the picture the route switches to the respective details page of the movie/series
What happens if the user wants to go back to the list / overview page? Therefore an additional AC should be
-[ ]  when clicking/tapping on the "go back to list" Link, the user is redirected to the landing page 

**Task**
- title as a h2 ->> for semantic reasons every page should have a `<h1>` element, therefore I recommend using it instead of the `<h2>` element.

**Comment by JessicaLoers** [comment]
The complexity is   😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁😁

**Comment by gaiisay** [comment]
Looks good now I think. Just a small suggestion: you can add the "go back to list" link to your wireframe.
