### ISSUE TITLE
i want to see a header

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#4]
## Value Proposition
​
**As a** user
**i want** to see a header
**so that I** know the name of the app.
​

## Description
![Image](https://user-images.githubusercontent.com/113838567/202465602-8b3fc69a-b584-4c27-8287-7a74282ab978.png)

## Acceptance Criteria
​
- [x] a place holder app name is visible on the top of the landing page
​

## Tasks
​
- [x] create a feature branch called header-feature
- [x] create a header component
- [x] styling in globalstyles.js
- [x] export the header component to _app.js

# Complexity Estimation
S

**Comment by Kheirah** [comment]
Looking forward to seeing that header come to live!
