### ISSUE TITLE
i want to create a favorites list

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#6]
## Value Proposition

**As a** user
**I want to** add create a list
**so that** i can see my favorite movies on a separate page.
​

## Description
![Image](https://user-images.githubusercontent.com/113838567/204135914-6c422f1d-0912-4295-a9d5-596c4de229c7.png)

## Acceptance Criteria

- [x] there is a toggle button on the details page
- [x] there is a favorites page
- [x] the toggle button adds/removes an item to/from the favorites page
- [x] the added series/movie appears on the favorites page
- [x] the removed item disappears from the favorites page
- [x] theres a link on the faves leading back to "home"
- [x] theres a link on the "home" page leading to the favorites page

## Tasks

- [x] create a new branch called toggle-feature
- [x] add a toggle button to the details page
- [x] add the toggled item to local storage
- [x] create a (temporary) favorites page using the squarelist component 
- [x] use link from next/link to connect landing page and faves pages

## Complexity

XXXXXXXL

**Comment by kai-franke** [comment]
Hi Will!
Great feature, great story! 😄 
I have one question/remark: You're calling the `add` button a `toggle` but you show and describe only an `add` button. Did you plan for the button to change to a `remove` button after adding a movie? Then you should describe this functionality. If this is not planned, you should simply call the button `button` and not `toggle`.

**Comment by WilhelmAlfke** [comment]
hey @kai-franke,
 indeed, i want it to function as a remove button when it was clicked. i will clarify this in my user story. thanks for the feeback.
