### ISSUE TITLE
create a favourites list

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#8]
## Value Proposition
​
**As a** user
**I want to** have favorites list
**so that** i can see which movies i added.
​
## Description
![Image](https://user-images.githubusercontent.com/113838567/203374098-1f9de244-b07e-4da1-a154-df413b0cdf51.png)

## Acceptance Criteria
​
- [ ] each picture on the landing page has a delete button
- [ ] clicking the button removes the picture from the landing page
- [ ] only items added to the favorites list are shown on the landing page
- [ ] items previously fetched from the array are not shown on the landing page
​

## Tasks
​
- [ ] create a branch called fave-feature
- [ ] create a delete button for each movie/series item on landing page
- [ ] remove deleted items from local storage
- [ ] write a function that only displays "added" items on the landing page

Complexity Estimation
S

**Comment by MeenaFoerderer** [comment]
Nice feature! 
Only two small remarks:

1. You should display the delete button that you want to implement in your description figure.

2. Typo in your value proposition:

> **so that ** i can see which movies i added.

Remove the space before the asterisks for formatting.
