### ISSUE TITLE
create a search bar

### ISSUE THREAD

**Issue by WilhelmAlfke** [WilhelmAlfke/capstone#9]
## Value Proposition
​
**As a** user
**I want to** have a search bar
**so that** I can search for any series/movie.
​
## Description
![Image](https://user-images.githubusercontent.com/113838567/204288495-5a5e9665-1bad-4a3b-9558-1437c3ebab1e.png)

## Acceptance Criteria
​
- [x] a search field is displayed on the landing page
- [x] the search bar can use any string of letters and numbers
- [x] when entering any word or number the landing page displays temporary results

## Tasks
​
- [x] create a branch called search-feature
- [ ] use search bar component from a react library
- [x] delete the squarelist component
- [x] display the results on the landing page

Complexity Estimation
L
